import { slugify, extractTags } from "./utils";
import { generateAISummary } from "./ai";
import { Video } from "./types";
const API_BASE="https://www.googleapis.com/youtube/v3";
function requireEnv(name:string){const v=process.env[name]; if(!v) throw new Error(`Missing env var: ${name}`); return v;}
async function yt<T>(url:string):Promise<T>{const res=await fetch(url,{cache:"no-store"}); if(!res.ok){throw new Error(`YouTube API error ${res.status}: ${await res.text()}`)} return res.json();}
export async function getUploadsPlaylistId(){const key=requireEnv("YOUTUBE_API_KEY"); const channelId=requireEnv("YOUTUBE_CHANNEL_ID"); const data:any=await yt(`${API_BASE}/channels?part=contentDetails&id=${channelId}&key=${key}`); const pid=data.items?.[0]?.contentDetails?.relatedPlaylists?.uploads; if(!pid) throw new Error("Could not find uploads playlist"); return pid;}
export async function getAllUploadVideoIds(){const key=requireEnv("YOUTUBE_API_KEY"); const playlistId=await getUploadsPlaylistId(); let pageToken=""; const ids:string[]=[]; do { const url=new URL(`${API_BASE}/playlistItems`); url.searchParams.set("part","snippet"); url.searchParams.set("playlistId",playlistId); url.searchParams.set("maxResults","50"); url.searchParams.set("key",key); if(pageToken) url.searchParams.set("pageToken",pageToken); const data:any=await yt(url.toString()); for(const item of data.items||[]){const id=item.snippet?.resourceId?.videoId; if(id) ids.push(id)} pageToken=data.nextPageToken||""; } while(pageToken); return Array.from(new Set(ids));}
export async function getVideosByIds(ids:string[]){const key=requireEnv("YOUTUBE_API_KEY"); const chunks=[] as string[][]; for(let i=0;i<ids.length;i+=50) chunks.push(ids.slice(i,i+50)); const out:Video[]=[]; for(const chunk of chunks){ const url=new URL(`${API_BASE}/videos`); url.searchParams.set("part","snippet,contentDetails"); url.searchParams.set("id",chunk.join(",")); url.searchParams.set("key",key); const data:any=await yt(url.toString()); for(const item of data.items||[]){ const title=item.snippet?.title||"Untitled video"; const description=item.snippet?.description||""; const publishedAt=item.snippet?.publishedAt||new Date().toISOString(); const thumbnail=item.snippet?.thumbnails?.high?.url||item.snippet?.thumbnails?.medium?.url||item.snippet?.thumbnails?.default?.url||""; const tags=extractTags(title,description); out.push({id:item.id,slug:slugify(title),title,description,publishedAt,thumbnail,url:`https://www.youtube.com/watch?v=${item.id}`,embedUrl:`https://www.youtube.com/embed/${item.id}`,duration:item.contentDetails?.duration,tags,year:new Date(publishedAt).getFullYear(),aiSummary:generateAISummary({title,tags}),aiTone:"funny"}); }} return out.sort((a,b)=>+new Date(b.publishedAt)-+new Date(a.publishedAt));}
export async function fetchFullChannelCatalog(){const ids=await getAllUploadVideoIds(); return getVideosByIds(ids);}
